Fix python issue on macOS 12.3 or later #152
firebase/firebase-unity-sdk pull request #176
Opened 2022-02-15 13:55 UTC by sableangle

### Description
> Provide details of the change, and generalize the change in the PR title above.

Auto detect the OS family and OS Version and change the return value of `PYTHON_INTERPRETER` property (also change the member type of this member), because of the new version macOS(after 12.3) will no longer shipped the Python2.

***
> Describe how you've tested these changes.

Tested on macOS 12.3 beta2, macOS 12.2, with Unity Editor 2020.3.x, Unity 2021.2.x
Not tested on earlier macOS version and earlier Unity Editor version.

***

### Type of Change
Place an `x` the applicable box:
- [x] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [ ] Other, such as a build process or documentation change.
***
Due to #154, the 'python' binary doesn't shipped with macOS after 12.3 (which is replace to 'python2.7' and 'python3').
So the Firebase.Editor script needs to change the binary file name if the macOS version is greater than 12.3. 
(Currently, just detect is the os version greater than 12 or not due to macOS 12 already shipped 'python3')

2022-02-15 19:01 UTC, cynthiajoan requested changes
Thanks for the PR. Your branch seems behind which introduced a lot none related diffs. Can you please pull and merge first so we can focus on the change?

2022-02-16 05:56 UTC, sableangle commented
HI, I was developing after the 'main' branch on my fork repo.
I was original set the base branch to 'master' is due to the contributing guidelines suggest me do so.
But I found most of the PR is setting the base branch to 'main', so I also change the base branch to 'main' on this PR, and then all others commits the required to  pull and merge should gone.

I'm not sure is this action acceptable, but if it is then I think we can continue the pull requires proccesse.

2022-02-17 05:01 UTC, sableangle reviewed
Auto detect the OS family and OS Version and change the return value of PYTHON_INTERPRETER

2022-02-17 10:26 UTC, sableangle commented
I also tested on macOS 11 with Unity2021.2.x
it works great!

2022-03-15 03:22 UTC, sableangle commented
Hi, macOS 12.3 is release today.
The old version SDK will soon unworkable on the Mac which update to the new version macOS.

Any suggestion on the PR? Any thing I can help to improve the python implementation, I will do the modify.

2022-03-15 14:08 UTC, xysverma commented
@cynthiajoan L Could it be taken forward. MacOS released today and i upgraded and i am blocked from using firebase due to this.

2022-03-19 08:24 UTC, closed without merging